### ISSUE TITLE
Secure Elasticsearch backend

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#19]
Password authentication. Limit Max query results

**Comment by demirdagemir** [comment]
Please bear in mind that these two lines in docker-compose.yml, enables the webpack-dev-server to communicate with elasticsearch server.

`http.cors.enabled=true`
`http.cors.allow-origin=* `

Otherwise it throws this error:
`No 'Access-Control-Allow-Origin' header is present on the requested
resource. Origin 'localhost:8080' is therefore not allowed access.`

**Comment by syncall** [comment]
Outdated
