### ISSUE TITLE
Single Page Application

### ISSUE THREAD

**Issue by joern-vh** [MusicConnectionMachine/VisualizationG6#43]
Create a Single-Page Application including
- Search Component #56 
- Autocompletion #57 
- Pagination Component #49 

@syncall @demirdagemir

**Comment by gyachdav** [comment]
Update on this one?

**Comment by syncall** [comment]
actually we did split this up into three issues.

**Comment by demirdagemir** [comment]
@gyachdav The latest one is #55, integrating timeline from G5. This is about to be done, I just have to work on the styling a little bit more. I did the first commit on the related branch, and the timeline component can be accessed from `/timeline`

Related to the description of this issue:

#56 is already done, of course we have to include the API with the real data. Since we are using react router, we already have a SPA since the first day. What we have to do is gather up all the components together from G5 and us, once they are finished.

#57 We have a issue for this, but I'm not sure if this is necessary because we integrated redux, which gives us search results as we type.

#49 @yetolas is working on this.

**Comment by kordianbruck** [comment]
Dismissed in favor of #72
