### ISSUE TITLE
Implement Pagination

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#49]
Ether Copy & Paste the Pagination from Group 1 or implemnt own bootstrap pagination. 

If Group 1 does not use Bootstrap approach 2 might be better for the look and feel
http://getbootstrap.com/components/#pagination

**Comment by yetolas** [comment]
Working on it, will update soon!

**Comment by kordianbruck** [comment]
@syncall you mean Group 5 right?

**Comment by yetolas** [comment]
That's what I checked, Group 5! I was working on what he suggested, trying to implement our own bootstrap pagination.

**Comment by kordianbruck** [comment]
@yetolas maybe you can copy something from here as well? https://github.com/MusicConnectionMachine/VisualizationG5/pull/50#pullrequestreview-30128791

**Comment by yetolas** [comment]
Yeah, I tried to fix my initial code who for some reason ddin't work exactly as I wanted. But I already had a look there to adjust so I can finally commit it!

**Comment by lustoykov** [comment]
Hi G6,

we have implemented a full Pagination component with bootstrap, you're welcome to use it

https://github.com/MusicConnectionMachine/VisualizationG5/pull/34

```js
      <Pagination
         EntityComponent={Composer}
         SuggestionComponent={Suggestion}
         title="Composers"
         entities={composers}
         query={query}
         showSuggestions={showSuggestions}
         suggestions={suggestions}
         currentPage={currentPage}
         limit={limit}
         loading={loading}
         offset={0}
         entitiesTotalCount={composersTotalCount}
         handleSearchChange={_query => this.onSearchChange(_query)}
         handleSearchClick={() => this.onSearchClick()}
         handlePageClick={page => this.onPageClick(page)}
         handleSuggestionClick={suggestion => this.onSuggestionClick(suggestion)}
      />
```

The implementation in https://github.com/MusicConnectionMachine/VisualizationG5/pull/50#pullrequestreview-30128791 is not as powerful, because it doesn't load data on demand (we don't need that there - instead we load all max 25-30 relations at once and split them into pages, since only 5 pages can fit the screen anyways). The Pagination component on the other hand is meant to scale for millions of entities and loads data on demand.

**Comment by pfent** [comment]
@yetolas any updates on this?

**Comment by yetolas** [comment]
I have tried to add this to our project: https://github.com/vayser/react-js-pagination for the pagination but there are still some errors I haven't fixed and still trying to make it work the way it should.

**Comment by kordianbruck** [comment]
@yetolas what about using the above component as mentioned?

**Comment by kordianbruck** [comment]
Widgets themselves will have pagination. This is obsolete.

For search results: show first 100 entries.
