### ISSUE TITLE
Enable webpack code splitting

### ISSUE THREAD

**Issue by syncall** [MusicConnectionMachine/VisualizationG6#60]
Webpack has a feature to split the bundle at certain breakpoints, and load the data on demand. We could use that to increase loading time a lot (split between a bare minimum, the search and the details). 
Maybe with some fancy loading icon in between.

**Comment by syncall** [comment]
I think for this all the includes done in App.js for bootstrap, css etc. have to be moved to every location they are used. 

So we have the statements at least twice, at the search file and the details file or else if the details page is loaded directly without opening the search page some files are missing.

**Comment by syncall** [comment]
Maybe we can also split the react source files into a separate bundle so they can be cached (nice to have)

**Comment by demirdagemir** [comment]
True.. I believe it's better practice to include parts of the css rather than, one big css file. Kind of structured it that way because it was easy at first. BUT, this issue will be solved when I integrate the timeline from G5, because they are using a different version of bootstrap; I'll migrate ours to that one and restructure the files.

**Comment by syncall** [comment]
This is what I though:
https://webpack.js.org/guides/code-splitting-require/
Or https://webpack.js.org/guides/code-splitting-import/

**Comment by kordianbruck** [comment]
Great idea. Not needed at the moment tho. We need the website finished up.
