### ISSUE TITLE
Wireframes and flow for SPA

### ISSUE THREAD

**Issue by gyachdav** [MusicConnectionMachine/VisualizationG6#62]
Is there flow description for the SPA? 

Are there any wireframes for the pages?

**Comment by gyachdav** [comment]
Still waiting to hear on that....

**Comment by syncall** [comment]
We did start with this (@yetolas did this): http://6ua191.axshare.com/#g=1&p=home

We did this on the first day but it was not so much help so we did't continue making them.

**Comment by gyachdav** [comment]
Can we still know what you're going for? Is there a demo of the SPA we can look at? A description of the flow? Some idea about themes, styles and assets?

**Comment by demirdagemir** [comment]
I mean, we had an SPA since the first day, our project is structured in that way. The demo is [here](http://webpageg6.8ed630ce.svc.dockerapp.io/). We will continue to integrate G5's work into our SPA and work on the issues we created here. Not sure what else to add regarding the SPA, or if there are any other requirements.

**Comment by ysdevys** [comment]
should I reassign this to @demirdagemir or should this issue be closed?

**Comment by ysdevys** [comment]
isn't this issue part of https://github.com/MusicConnectionMachine/VisualizationG6/issues/43

**Comment by kordianbruck** [comment]
Can you guys just describe in 2-3 sentences what the usual progression through the app is? This will resolve this issue. Like so:
1. Go on Website
2. Search for ...
3. ???
4. Profit!

**Comment by syncall** [comment]
Basically the Idea was a Site to explore the entities of the Databse (True we did not focus on relations so much, because we could not really think about what to do with them)

1. I am looking for some new information for Mozart
2. I visit the website
3. I search for Mozart 
4. I'll get a lot of Information regarding Mozart (Musician, Composers, Pieces in a list)

Version A:
5. The first entry should be the Musician Mozart - I click it
6. We present as much structured Information as possible regarding Mozart and all connections to the other entries(like his pieces). I can explore these as well as the relations through the Widget of Team 5
7. I found out some new interesting stuff about Mozart

Version B:
5. Before even exploring the entities I get some interesting relation presented regarding Mozart
6. Cool, now I know Loepold Mozart was the father of Amadeus Mozart

**Comment by vviro** [comment]
@syncall So how does the step 4 work? Is there one paginated table with musicians, composers and compositions? Three separate tables? Does the widget of Group 5 open upon a click on an entity from the tables (step 6A)?

I would not really consider the relation "composer - composition" an interesting relation for our purposes. It is rather trivial and for example the IMSLP already has exactly this: a paginated list of compositions of a composer.

Any suggestions as to how 5B should be implemented?

**Comment by syncall** [comment]
Yes we though of putting everything in one table (the Google like search mentioned in the Milestones) - but the sample data only included compositions so until now we only have that

When clicking on a search result we open a 'detail' page. There we can put all the different items we have. Graph/Timeline/Map/description of the entity/relations to other entities
-> a complete set of our information (you would not have to switch between IMSLP and our App to find what you need)

It is true that this is similar to IMSLP. Only here we would not be limited to a very small space(we have the full page). And as far as I understood the other Teams are collecting an incredible amount of new data, which (unless feeded back to IMSLP) would not be accessable by the user.

Regarding 5B, there is already something in the demo. It only pops up if we have data, and the data is very limited. Try Mozart.

**Comment by kordianbruck** [comment]
Ok - thanks for the explanation. Lets close this then.
