### ISSUE TITLE
Integrate search via API

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#71]
Depending on https://github.com/MusicConnectionMachine/api/issues/27

We want to search the real data.

**Comment by ysdevys** [comment]
hey guys sorry I have exams this and next week and couldn't do anything yet.
I will try to integrate the Search API, but can someone give me the whole paths for the endpoints because it seems that I can't find them in https://github.com/MusicConnectionMachine/api/blob/develop/api/controllers/search.js 
I see here just:
```
function searchString(req, res) {
    res.status(501);
    res.json('Not implemented!');
}
```
All other searches are just partial as I can see: searchRelations, searchEntities.
And we actually need exactly this function/endpoint for searching just a string.
... Or I'm missing something?

**Comment by kordianbruck** [comment]
@ysdevys its currently being merged: https://github.com/MusicConnectionMachine/api/pull/114
